In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('raw_accepted_2007_to_2018q4.csv', low_memory=False)

In [3]:
df1.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df1.shape

(2260701, 151)

In [5]:
# Check how many columns are there 
print("Total columns:", len(df1.columns))

Total columns: 151

In [6]:
# Show all column names
print(df1.columns.tolist())

['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc', 'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line', 'fico_range_low', 'fico_range_high', 'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc', 'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 'recoveries', 'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d', 'last_fico_range_high', 'last_fico_range_low', 'collections_12_mths_ex_med', 'mths_since_last_major_derog', 'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint', 'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit', 'revol_bal_joint', 'sec_app_fico_range_low', 'sec_app_fico_range_high', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog', 'hardship_flag', 'hardship_type', 'hardship_reason', 'hardship_status', 'deferral_term', 'hardship_amount', 'hardship_start_date', 'hardship_end_date', 'payment_plan_start_date', 'hardship_length', 'hardship_dpd', 'hardship_loan_status', 'orig_projected_additional_accrued_interest', 'hardship_payoff_balance_amount', 'hardship_last_payment_amount', 'disbursement_method', 'debt_settlement_flag', 'debt_settlement_flag_date', 'settlement_status', 'settlement_date', 'settlement_amount', 'settlement_percentage', 'settlement_term']

In [7]:
# Define the 21 key columns
selected_columns = [
    "annual_inc",
    "emp_length",
    "home_ownership",
    "addr_state",
    "loan_amnt",
    "term",
    "int_rate",
    "installment",
    "purpose",
    "issue_d",
    "fico_range_low",
    "fico_range_high",
    "open_acc",
    "revol_bal",
    "revol_util",
    "total_acc",
    "dti",
    "loan_status",
    "last_pymnt_d",
    "last_pymnt_amnt",
    "recoveries"
]

In [8]:
# Keep only those columns
df1_selected = df1[selected_columns]

# Quick check
print(df1_selected.shape)
print(df1_selected.head())

(2260701, 21)
   annual_inc emp_length home_ownership addr_state  loan_amnt        term  \
0     55000.0  10+ years       MORTGAGE         PA     3600.0   36 months
1     65000.0  10+ years       MORTGAGE         SD    24700.0   36 months
2     63000.0  10+ years       MORTGAGE         IL    20000.0   60 months
3    110000.0  10+ years       MORTGAGE         NJ    35000.0   60 months
4    104433.0    3 years       MORTGAGE         PA    10400.0   60 months

   int_rate  installment             purpose   issue_d  ...  fico_range_high  \
0     13.99       123.03  debt_consolidation  Dec-2015  ...            679.0
1     11.99       820.28      small_business  Dec-2015  ...            719.0
2     10.78       432.66    home_improvement  Dec-2015  ...            699.0
3     14.85       829.90  debt_consolidation  Dec-2015  ...            789.0
4     22.45       289.91      major_purchase  Dec-2015  ...            699.0

   open_acc  revol_bal  revol_util  total_acc    dti  loan_status  \
0       7.0     2765.0        29.7       13.0   5.91   Fully Paid
1      22.0    21470.0        19.2       38.0  16.06   Fully Paid
2       6.0     7869.0        56.2       18.0  10.78   Fully Paid
3      13.0     7802.0        11.6       17.0  17.06      Current
4      12.0    21929.0        64.5       35.0  25.37   Fully Paid

  last_pymnt_d last_pymnt_amnt  recoveries
0     Jan-2019          122.67         0.0
1     Jun-2016          926.35         0.0
2     Jun-2017        15813.30         0.0
3     Feb-2019          829.90         0.0
4     Jul-2016        10128.96         0.0

[5 rows x 21 columns]

In [9]:
df1_selected.to_csv('accepted_data.csv', index=False)

In [10]:
df1_selected['installment'].max()

1719.83

In [11]:
df1_selected.dtypes

annual_inc         float64
emp_length          object
home_ownership      object
addr_state          object
loan_amnt          float64
term                object
int_rate           float64
installment        float64
purpose             object
issue_d             object
fico_range_low     float64
fico_range_high    float64
open_acc           float64
revol_bal          float64
revol_util         float64
total_acc          float64
dti                float64
loan_status         object
last_pymnt_d        object
last_pymnt_amnt    float64
recoveries         float64
dtype: object

In [12]:
df1_selected.isnull().sum()

annual_inc             37
emp_length         146940
home_ownership         33
addr_state             33
loan_amnt              33
term                   33
int_rate               33
installment            33
purpose                33
issue_d                33
fico_range_low         33
fico_range_high        33
open_acc               62
revol_bal              33
revol_util           1835
total_acc              62
dti                  1744
loan_status            33
last_pymnt_d         2460
last_pymnt_amnt        33
recoveries             33
dtype: int64

In [13]:
df2 = pd.read_csv('raw_rejected_2007_to_2018Q4.csv')

In [14]:
df2.head()

,Amount Requested,Application Date,Loan Title,Risk_Score,Debt-To-Income Ratio,Zip Code,State,Employment Length,Policy Code
0,1000.0,2007-05-26,Wedding Covered but No Honeymoon,693.0,10%,481xx,NM,4 years,0.0
1,1000.0,2007-05-26,Consolidating Debt,703.0,10%,010xx,MA,< 1 year,0.0
2,11000.0,2007-05-27,Want to consolidate my debt,715.0,10%,212xx,MD,1 year,0.0
3,6000.0,2007-05-27,waksman,698.0,38.64%,017xx,MA,< 1 year,0.0
4,1500.0,2007-05-27,mdrigo,509.0,9.43%,209xx,MD,< 1 year,0.0

In [15]:
df2.shape

(27648741, 9)

In [16]:
df2.dtypes

Amount Requested        float64
Application Date         object
Loan Title               object
Risk_Score              float64
Debt-To-Income Ratio     object
Zip Code                 object
State                    object
Employment Length        object
Policy Code             float64
dtype: object

In [17]:
df2.columns = df2.columns.str.lower()
df2.columns = df2.columns.str.replace(' ', '_')
df2.columns

Index(['amount_requested', 'application_date', 'loan_title', 'risk_score',
       'debt-to-income_ratio', 'zip_code', 'state', 'employment_length',
       'policy_code'],
      dtype='object')

In [18]:
df2.columns = df2.columns.str.replace('-', '_')
df2.columns

Index(['amount_requested', 'application_date', 'loan_title', 'risk_score',
       'debt_to_income_ratio', 'zip_code', 'state', 'employment_length',
       'policy_code'],
      dtype='object')

In [19]:
df2.dtypes

amount_requested        float64
application_date         object
loan_title               object
risk_score              float64
debt_to_income_ratio     object
zip_code                 object
state                    object
employment_length        object
policy_code             float64
dtype: object

In [20]:
df2.to_csv('rejected_data.csv', index=False)

In [21]:
df2.isnull().sum()

amount_requested               0
application_date               0
loan_title                  1305
risk_score              18497630
debt_to_income_ratio           0
zip_code                     293
state                         22
employment_length         951355
policy_code                  918
dtype: int64

In [22]:
df2.shape

(27648741, 9)

In [23]:
!pip install psycopg2-binary pandas sqlalchemy
import psycopg2

Requirement already satisfied: psycopg2-binary in c:\users\shubhangi\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: pandas in c:\users\shubhangi\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in c:\users\shubhangi\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: numpy>=1.26.0 in c:\users\shubhangi\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shubhangi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shubhangi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shubhangi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in c:\users\shubhangi\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\shubhangi\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\shubhangi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [24]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
dbname = 'credit_risk_analysis'
user = 'postgres'
password = 'Postgresql1999%40' #Pw is 'Postgresql1999@' use %40 in place of @ to not get any error in connection_string
host = 'localhost' # or remote host IP
port = '5432' # default port

# Create the connection string for SQLAlchemy
connection_string = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{dbname}"
engine = create_engine(connection_string)

In [25]:
# 2. Load only required columns (reduces memory usage)
query = """SELECT loan_amnt, annual_inc, dti, ROUND((fico_range_low + fico_range_high)/2, 2) AS fico_score, 
            purpose, default_flag FROM lending_club_selected;"""
# Use chunksize if dataset is huge
df_iter = pd.read_sql(query, engine, chunksize=100000)

In [27]:
import dask.dataframe as dd   # for large-scale data handling

# Concatenate chunks into Dask DataFrame for scalability
df = dd.from_pandas(pd.concat(df_iter), npartitions=8)

In [28]:
# 3. Basic Cleaning
# Drop missing values quickly
df = df.dropna()

In [31]:
# Convert categorical 'purpose' into dummy variables
df = df.categorize(columns=['purpose'])
df = dd.get_dummies(df, columns=['purpose'], drop_first=True)

In [32]:
# 4. Features & Target
X = df.drop('default_flag', axis=1)
y = df['default_flag']

In [33]:
# Convert to pandas for modeling (sample if extremely large)
X = X.compute()
y = y.compute()

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [35]:
# 5. Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [36]:
# 6. Scale Features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [37]:
# 7. Train Fast Model (Logistic Regression with saga solver for large data)
model = LogisticRegression(max_iter=500, solver='saga', n_jobs=-1)
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=500, n_jobs=-1, solver='saga')

In [38]:
# 8. Evaluate
y_pred = model.predict(X_test_scaled)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

         0.0       0.80      1.00      0.89    215290
         1.0       0.39      0.00      0.01     53698

    accuracy                           0.80    268988
   macro avg       0.59      0.50      0.45    268988
weighted avg       0.72      0.80      0.71    268988

In [39]:
# 9. Feature Importance
importance = pd.Series(model.coef_[0], index=X.columns)
print("\nTop Features:\n", importance.sort_values(ascending=False).head(10))

Top Features:
 loan_amnt                     0.321923
dti                           0.194136
purpose_small_business        0.081872
purpose_other                 0.069104
purpose_moving                0.042289
purpose_medical               0.039164
purpose_major_purchase        0.034241
purpose_debt_consolidation    0.024475
purpose_house                 0.023171
purpose_home_improvement      0.022009
dtype: float64